name: example
description: An example web application with webapp package dart.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_web_compilers: 
  test:
  dart_dev: 
  build_runner:
  json_serializable:

dependencies:
  webapp:
    # path: ../
  watcher: